version: '3.7'

services:
  bot:
    env_file:
      - .env.wire
      - .env.wire.secret
    networks:
      - charon-onboarding-bot
    depends_on:
      - charon

  charon:
    image: lukaswire/charon
    container_name: onboarding-bot-charon
    env_file:
      - .env.wire
    ports:
      - 8080:8080
    networks:
      - charon-onboarding-bot
      - charon-proxy-redis
    depends_on:
      - redis

  redis:
    image: redis:5.0.8-alpine
    ports:
      - 6379:6379
    volumes:
      - ./db_config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - charon-proxy-redis


networks:
  charon-onboarding-bot:
    driver: bridge
  charon-proxy-redis:
    driver: bridge