version: '3'

services:
  bot:
    env_file:
      - .env
      - .env.wire
    networks:
      - charon-onboarding-bot
    depends_on:
      - charon

  charon:
    image: lukaswire/charon
    container_name: charon-onboarding-bot
    env_file:
      - .env
      - .env.wire
    ports:
      - 8080:8080
    networks:
      - charon-onboarding-bot


networks:
  charon-onboarding-bot:
    driver: bridge